config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # resources :users
  resources :friends do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :destroy, :update, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

# root to: 'lists#index'
# resources :lists, except: [:edit, :update] do
#   resources :bookmarks, only: [:new, :create]
#   resources :reviews, only: :create
# end
# resources :bookmarks, only: :destroy
# resources :reviews, only: :destroy
# end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  validates :location, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  belongs_to :user
  belongs_to :friend
end

app/models/friend.rb
class Friend < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :age, numericality: { only_integer: true }, presence: true
  validates :location, presence: true
  validates :gender, presence: true
  validates :price, numericality: { only_integer: true }, presence: true
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # validates :name, presence: true, uniqueness: true
  validates :password, presence: true
  validates :email, presence: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
  # validates :bio, presence: true
  has_many :bookings
  has_many :friends, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @friends_bookings = Booking.all.select do |booking|
      booking.friend.user == current_user
    end
    @accepted_bookings = current_user.bookings.select do |booking|
      booking.approved == true
    end
    @pending_bookings = current_user.bookings.select do |booking|
      booking.approved.nil?
    end
  end



  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.friend = Friend.find(params[:friend_id])
    if @booking.save!
      redirect_to friends_path, notice: "Made a new booking! :)"
    else
      render "friends/index"
    end
  end

  def update
    @booking_request = Booking.find(params[:id])
    @booking_request.approved = true
    @booking_request.save
    @friends_bookings = Booking.all.select do |booking|
      booking.friend.user == current_user && booking.approved = false
    end
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :location)
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController

  def new
    @friend = Friend.new
  end

  def create
    @friend = Friend.new(friend_params)
    @friend.user = current_user
    if @friend.save
      redirect_to @friend, notice: "Made a new friend! :)"
    else
      render :new
    end
  end

  def show
    @friend = Friend.find(params[:id])
    @booking = Booking.new
  end

  def index
    @friends = Friend.all.shuffle
  end

  private

  def friend_params
    params.require(:friend).permit(:name, :age, :location, :interest, :gender, :price, :photo, :bio)
  end
  def edit
    @friend = Friend.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<br>
<br>

<div class="container">

  <!-- Tabs -->

  <ul class="nav nav-tabs nav-fill" id="myTab" role="tablist">
    <li class="nav-item" role="presentation">
      <button class="nav-link active" id="upcoming-tab" data-bs-toggle="tab" data-bs-target="#upcoming" type="button" role="tab" aria-controls="upcoming" aria-selected="true">Accepted bookings</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="pending-tab" data-bs-toggle="tab" data-bs-target="#pending" type="button" role="tab" aria-controls="pending" aria-selected="false">Pending bookings</button>
    </li>
    <li class="nav-item" role="presentation">
      <button class="nav-link" id="request-tab" data-bs-toggle="tab" data-bs-target="#request" type="button" role="tab" aria-controls="request" aria-selected="false">Active Requests</button>
    </li>
      <li class="nav-item" role="presentation">
      <button class="nav-link" id="contact-tab" data-bs-toggle="tab" data-bs-target="#contact" type="button" role="tab" aria-controls="contact" aria-selected="false">Request history</button>
    </li>
  </ul>

  <!-- upcoming(accepted) -->
  <div class="tab-content" id="myTabContent">

    <div class="tab-pane fade show active" id="upcoming" role="tabpanel" aria-labelledby="upcoming-tab">
      <h1 class="text-center pt-5"> Accepted Bookings</h1>
      <div class="index-cards">
        <% @accepted_bookings.each do |booking| %>
          <%= link_to friend_path(booking.friend.id) do %>
            <%= cl_image_tag booking.friend.photo.key,
            width: 400, height: 300, crop: :fill %>
            <div class="friend-info">
              <p>Name: <%= booking.friend.name %></p>
              <p>Age: <%= booking.friend.age %></p>
              <p>Location: <%= booking.location %></p>
              <p>Date of Booking: <%= booking.start_date %> - <%= booking.end_date %></p>
              <% if booking.approved %>
                <p>Booking has been accepted</p>
              <% else %>
                <p>Booking pending</p>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
 

    <!-- Pending bookings -->

    <div class="tab-pane fade" id="pending" role="tabpanel" aria-labelledby="pending-tab">
      <h2 class="text-center pt-5">Pending Bookings</h2>
      <div class="index-cards">
        <% @pending_bookings.each do |booking| %>
          <%= link_to friend_path(booking.friend.id) do %>
            <%= cl_image_tag booking.friend.photo.key,
            width: 400, height: 300, crop: :fill %>
            <div class="friend-info">
              <p>Name: <%= booking.friend.name %></p>
              <p>Age: <%= booking.friend.age %></p>
              <p>Location: <%= booking.location %></p>
              <p>Date of Booking: <%= booking.start_date %> - <%= booking.end_date %></p>
              <% if booking.approved %>
                <p>Booking has been accepted</p>
              <% else %>
                <p>Booking pending</p>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

    <div class="tab-pane fade" id="request" role="tabpanel" aria-labelledby="request-tab">
      <h1 class="text-center pt-5"> Requests to book my friends </h1>
      <div class="index-cards">
        <% @friends_bookings.each do |booking| %>
        <div>
          <%= cl_image_tag booking.friend.photo.key,
          width: 400, height: 300, crop: :fill %>
          <div class="friend-info">
            <p> Name: <%= booking.friend.name %> </p>
            <p>Age: <%= booking.friend.age %></p>
            <p> Requested by: <%= booking.user.name %> </p>
            <p> Location: <%= booking.location %> </p>
            <p> Date of Booking: <%= booking.start_date %> - <%= booking.end_date %></p>
              <%= link_to "Approve Request", booking_path(booking), method: :patch %>
              <%= link_to "Reject Request", booking_path(booking), method: :patch %>
          </div>
          </div>
          <% end %>
       </div>
    </div>

  </div>

</div>
<%# Add edit button to change status
Need to show the user who is trying making the booking %>

app/views/friends/edit.html.erb
<h1>Edit Friend</h1>
<br>
<%= form_for(@friend) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :age %>
  <%= f.text_field :age %>
  <br>
  <%= f.label :gender %>
  <%= f.text_field :gender %>
  <br>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <br>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <br>
  <%= f.submit %>
<% end %>

app/views/friends/index.html.erb
<div class="container">
<h3 class="text-center pt-5 ">There are <%= Friend.count %> Friends Available Now</h3>

<div class="index-cards">
  <% @friends.each do |friend| %>
    <%= link_to friend_path(friend) do %>
    <div class="friend-card">
    <% if friend.photo.attached? %>
      <%= cl_image_tag friend.photo.key,
        width: 400, height: 150, crop: :fill, gravity: :face %>
    <% end %>
      <div class="friend-info">
        <h4> <%= friend.name %></h4>

        <p>Age: <%= friend.age %></p>
        <p>Interest: <%= friend.interest %></p>
        <p>Price: £<%= friend.price %> per session</p>

      </div>
    </div>
    <% end %>
  <% end %>
</div>


<%= link_to "back to home", root_path, class: "btn btn-gradient m-3"%></p>
</div>

app/views/friends/new.html.erb
<h1 class="p-5 text-center text-uppercase"> List a new friend!</h1>
<div class="container">
    <div class="card mx-auto" style="width: 550px">
      <div class="card-body">

      <%= simple_form_for(@friend) do |f| %>

        <%= f.input :name, label_html: { class: "fw-normal" } %>

        <%= f.input :age %>

        <%= f.input :gender %>

        <%= f.input :interest %>

        <%= f.input :location %>

        <%= f.input :price %>

        <%= f.input :photo, as: :file %>

        <%= f.input :bio %>

        <%= f.submit %>

      <% end %>

      <%= link_to "Go back", friends_path, class: "btn btn-gradient mt-5" %>
      </div>
    </div>
</div>

app/views/friends/show.html.erb
<br>
<br>
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <div>
      <% if @friend.photo.attached? %>
        <%= cl_image_tag @friend.photo.key,
          width: 600, height: 400, crop: :fill,  gravity: :face %>
      <% end %>
    </div>
    <div class="grid">
      <h1 class="text-center p-3"><%= @friend.name %>, <%= @friend.age %></h1>
      <h3 class="text-center p-3"> Listed by: <%= @friend.user.name %></h3>
    <div class="text-center">
      <h2><%= @friend.gender %> <br><%= @friend.location %></h2>
    </div>
    </div>
  </div>
  <hr>
  <div class="d-flex justify-content-between">
    <div class="w-50">
      <p>Hello everyone! This is my friend <%= @friend.name %>! <%= @friend.name %> is a really fun person, and loves <%= @friend.interest %>. <%= @friend.name %> would love to get to know you and hang out sometime!</p>
      <p><%= @friend.bio %></p>
        <hr>
    </div>
    <div class="booking-card booking-cards">
      <%= simple_form_for [@friend, @booking] do |f| %>
      <div class="form-start-date-start-date">
        <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :end_date , as: :string, required: false, input_html: {class: "datepicker"} %>
     </div>

      <%= f.input :location %>
      <%= f.submit "Request this friend!", class: "button-form" %>
      <% end %>
    </div>
  </div>
  <hr>
<%= link_to "back to index", friends_path, class: "btn btn-gradient"%></p>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAFriend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&family=Gaegu:wght@300&family=Ubuntu+Mono&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <div style="min-height: calc(100vh - 156px)">
    <%= yield %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.pinimg.com/originals/c9/57/2d/c9572d639f6de195651035bb779cfc07.jpg);">
  <div class="container">
    <h1>Lonely?</h1>
    <h2>Find friends and make genuine connections.</h2>
    <%= link_to "Explore friends", friends_path, class: "btn btn-flat" %>
  </div>
</div>

<br>

<%# card grid %>
<div class="container">
   <h2> Popular areas </h2>
   <br>
    <div class="cards">
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://i.guim.co.uk/img/media/78c88d474f6230337428610eaa45d4ab12d08745/0_251_3000_1799/master/3000.jpg?width=1200&height=1200&quality=85&auto=format&fit=crop&s=c420f1eedf2d81e155de0c6690010695)">
       Shoreditch
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1529156069898-49953e39b3ac?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8ZnJpZW5kc3xlbnwwfHwwfHw%3D&w=1000&q=80)">
       Islington
    </div>

    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/dinner.jpg)">
       Hamstead
    </div>
    </div>
</div>

<%# footer %>

app/views/shared/_footer.html.erb
    <div class="footer">
    <h4><strong>Contact us</strong></h4>
    <div class="footer-links">
        <a href="https://github.com/jimmehyuen"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="https://www.linkedin.com/in/jimmy-yuen"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
   <%= image_tag "logo.png" %>
  </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <p class="nav-link"><%= current_user.email %></p>
            </li>
            <li class="nav-item active">
              <a class="nav-link"<%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="/friends/new">List a friend</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/bookings">My Bookings</a>
            </li>
            <li class="nav-item dropdown">
              <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://avatars.githubusercontent.com/u/2978876?u=d018188079ab8ae8dc4bdac60ca40dea4cccbb0f&v=4" />
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">Notifications</a>
                <a class="dropdown-item" href="#">Settings</a>
              </div>
            </li>
            <!--li class="nav-item"-->
            <!--/li-->
        </ul>
      </div>
    <% else %>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/users/sign_in">Want to make some friends? <strong>Sign in</strong></a>
            </li>
            <!--li class="nav-item"-->
            <!--/li-->
        </ul>
      </div>
    <% end %>
  </div>
</div>